# Generated by Django 3.2 on 2021-05-10 07:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LevelJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(upload_to='logo')),
                ('location', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 5, 10, 7, 56, 9, 417970, tzinfo=utc))),
                ('dedline', models.DateField()),
                ('salary', models.CharField(max_length=50)),
                ('job_time', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('experience', models.TextField()),
                ('experience_time', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=100)),
                ('telegram_profile', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.ManyToManyField(to='jobs.LevelJob')),
            ],
        ),
    ]
