# Generated by Django 3.2 on 2021-05-04 04:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='jobsmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 4, 35, 46, 750332, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='jobsmodel',
            name='level',
            field=models.ManyToManyField(to='jobs.LevelJob'),
        ),
    ]
