# Generated by Django 3.1.7 on 2021-04-02 05:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210402_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 5, 10, 36, 41185, tzinfo=utc)),
        ),
    ]
