# Generated by Django 3.2 on 2021-05-04 06:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210504_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobsmodel',
            old_name='benifits',
            new_name='contact',
        ),
        migrations.AlterField(
            model_name='jobsmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 6, 30, 38, 177412, tzinfo=utc)),
        ),
    ]
