# Generated by Django 3.2 on 2021-05-04 06:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210504_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsmodel',
            name='contact',
        ),
        migrations.AddField(
            model_name='jobsmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='jobsmodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobsmodel',
            name='telegram_profile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobsmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 6, 47, 18, 985047, tzinfo=utc)),
        ),
    ]
