# Generated by Django 3.2 on 2021-04-27 17:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20210424_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 17, 42, 59, 680047, tzinfo=utc)),
        ),
    ]
