# Generated by Django 3.1.7 on 2021-04-07 07:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20210406_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 7, 4, 0, 85788, tzinfo=utc)),
        ),
    ]
