# Generated by Django 3.1.7 on 2021-03-24 18:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210324_1848'),
        ('tests', '0002_auto_20210324_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 24, 18, 48, 17, 549130, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='exam',
            name='tag',
        ),
        migrations.AddField(
            model_name='exam',
            name='tag',
            field=models.ManyToManyField(to='home.TagModel'),
        ),
    ]
