# Generated by Django 3.1.7 on 2021-03-24 18:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20210324_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(verbose_name='Javob'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 24, 18, 53, 52, 556, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(verbose_name='Savol'),
        ),
    ]
