# Generated by Django 3.2 on 2021-05-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryblog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_photo'),
        ),
    ]
