# Generated by Django 3.2 on 2021-05-05 03:29

import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_cardmodel_create_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 5, 8, 29, 50, 393237)),
        ),
        migrations.CreateModel(
            name='BlogUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='img')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('create_date', models.DateField(default=datetime.datetime(2021, 5, 5, 8, 29, 50, 398733))),
                ('count_of_view', models.IntegerField(default=0)),
                ('count_of_comment', models.IntegerField(default=0)),
                ('is_publish', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tag', models.ManyToManyField(to='home.TagModel', verbose_name='list_tag')),
            ],
        ),
    ]
