# Generated by Django 3.1.7 on 2021-04-02 04:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 2, 4, 58, 10, 419700)),
        ),
        migrations.AlterField(
            model_name='commentblogmodel',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 4, 58, 10, 424125, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='replycommentblogmodel',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 4, 58, 10, 425669, tzinfo=utc)),
        ),
    ]
