# Generated by Django 3.2 on 2021-05-06 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_categoryblog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='category_blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_blog', to='blogs.categoryblog'),
        ),
    ]
