# Generated by Django 3.2 on 2021-05-05 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_cardmodel_create_date'),
        ('blogs', '0002_auto_20210505_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 5, 8, 31, 47, 243225)),
        ),
        migrations.AlterField(
            model_name='blogusermodel',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 5, 8, 31, 47, 248638)),
        ),
        migrations.AlterField(
            model_name='blogusermodel',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='home.TagModel', verbose_name='list_tag'),
        ),
    ]
