# Generated by Django 3.2 on 2021-05-06 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20210505_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='is_publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 6, 15, 8, 50, 405490)),
        ),
        migrations.DeleteModel(
            name='BlogUserModel',
        ),
    ]
