# Generated by Django 3.1.7 on 2021-04-15 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20210414_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='count_of_blog',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='count_of_comment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 15, 12, 46, 37, 764660)),
        ),
    ]
