# Generated by Django 3.1.7 on 2021-04-23 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20210415_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 23, 12, 37, 6, 947041)),
        ),
    ]
