# Generated by Django 3.1.7 on 2021-04-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210414_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='books'),
        ),
    ]
