# Generated by Django 3.2 on 2021-04-29 12:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multichoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Enter the answer text that you want displayed', null=True, verbose_name='Content'),
        ),
    ]
