# Generated by Django 3.1.7 on 2021-03-15 06:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_info', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='img')),
                ('tag', models.ManyToManyField(to='home.TagModel', verbose_name='tag_list')),
            ],
        ),
        migrations.CreateModel(
            name='CourseListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs_name', models.CharField(max_length=100)),
                ('kurs_info', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='img')),
                ('date_of_kurs', models.DateField(default=datetime.datetime(2021, 3, 15, 11, 49, 49, 714015))),
                ('number_of_video', models.IntegerField()),
                ('hour_of_kurs', models.IntegerField()),
                ('minute_of_kurs', models.IntegerField()),
                ('number_of_saw', models.IntegerField()),
                ('number_of_comment', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tag', models.ManyToManyField(to='home.TagModel', verbose_name='tag_list')),
            ],
        ),
    ]
