# Generated by Django 3.1.7 on 2021-03-15 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('user', models.CharField(max_length=100)),
                ('user_image', models.ImageField(upload_to='user images')),
                ('text', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.datetime(2021, 3, 15, 13, 50, 39, 476212))),
            ],
        ),
        migrations.AddField(
            model_name='courselistmodel',
            name='course',
            field=models.ManyToManyField(to='courses.CourseModel'),
        ),
        migrations.AlterField(
            model_name='courselistmodel',
            name='date_of_kurs',
            field=models.DateField(default=datetime.datetime(2021, 3, 15, 13, 50, 39, 472213)),
        ),
    ]
