# Generated by Django 3.1.7 on 2021-03-23 09:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210323_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentcourse',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 23, 9, 5, 53, 621397, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='courselistmodel',
            name='date_of_kurs',
            field=models.DateField(default=datetime.datetime(2021, 3, 23, 14, 5, 53, 616398)),
        ),
        migrations.AlterField(
            model_name='replycommentcourse',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 23, 9, 5, 53, 622398, tzinfo=utc)),
        ),
    ]
