# Generated by Django 3.1.7 on 2021-03-15 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210315_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetailmodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 15, 14, 14, 24, 729152)),
        ),
        migrations.AlterField(
            model_name='courselistmodel',
            name='date_of_kurs',
            field=models.DateField(default=datetime.datetime(2021, 3, 15, 14, 14, 24, 725148)),
        ),
    ]
