# Generated by Django 3.1.7 on 2021-03-15 09:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210315_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetailmodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 15, 14, 33, 31, 790422)),
        ),
        migrations.RemoveField(
            model_name='coursedetailmodel',
            name='video',
        ),
        migrations.AlterField(
            model_name='courselistmodel',
            name='date_of_kurs',
            field=models.DateField(default=datetime.datetime(2021, 3, 15, 14, 33, 31, 785424)),
        ),
        migrations.CreateModel(
            name='CourseVideoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=1000)),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('video_time', models.BigIntegerField(max_length=999)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courselistmodel')),
            ],
        ),
        migrations.AddField(
            model_name='coursedetailmodel',
            name='video',
            field=models.ManyToManyField(to='courses.CourseVideoModel'),
        ),
    ]
