# Generated by Django 3.1.7 on 2021-03-24 14:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20210323_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentcourse',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 24, 14, 45, 42, 531986, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='courselistmodel',
            name='date_of_kurs',
            field=models.DateField(default=datetime.datetime(2021, 3, 24, 14, 45, 42, 524503)),
        ),
        migrations.AlterField(
            model_name='coursevideomodel',
            name='video_url',
            field=models.URLField(default='https://www.youtube.com/embed/'),
        ),
        migrations.AlterField(
            model_name='replycommentcourse',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 24, 14, 45, 42, 533732, tzinfo=utc)),
        ),
    ]
