# Generated by Django 3.1.7 on 2021-03-24 18:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20210324_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentcourse',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 24, 18, 53, 51, 977174, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='courselistmodel',
            name='date_of_kurs',
            field=models.DateField(default=datetime.datetime(2021, 3, 24, 18, 53, 51, 970302)),
        ),
        migrations.AlterField(
            model_name='replycommentcourse',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 24, 18, 53, 51, 979295, tzinfo=utc)),
        ),
    ]
