# Generated by Django 3.2 on 2021-05-07 02:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemanswermodeluser',
            name='send_answer_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 5, 7, 2, 45, 35, 144331, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
