# Generated by Django 3.2 on 2021-05-01 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemmodel',
            name='topictags',
        ),
        migrations.AddField(
            model_name='problemmodel',
            name='topic',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TopicTagModel',
        ),
    ]
