# Generated by Django 3.2 on 2021-05-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20210501_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemmodel',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
