# Generated by Django 3.2 on 2021-05-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_problemanswermodeluser_send_answer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemanswermodeluser',
            name='answer_error_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
