# Generated by Django 3.2 on 2021-05-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_alter_problemanswermodeluser_answer_error_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemanswermodeluser',
            name='is_waiting',
            field=models.BooleanField(default=True),
        ),
    ]
