# Generated by Django 3.2 on 2021-05-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_auto_20210501_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemmodel',
            name='sequence_number',
            field=models.CharField(max_length=10),
        ),
    ]
