# Generated by Django 3.1.7 on 2021-03-13 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmodel',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 13, 11, 28, 12, 727372)),
        ),
        migrations.RemoveField(
            model_name='cardmodel',
            name='tag',
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='tag',
            field=models.ManyToManyField(to='home.TagModel', verbose_name='tag_list'),
        ),
        migrations.AlterField(
            model_name='homemaqolamodel',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 13, 11, 28, 12, 730340)),
        ),
        migrations.RemoveField(
            model_name='homemaqolamodel',
            name='tag',
        ),
        migrations.AddField(
            model_name='homemaqolamodel',
            name='tag',
            field=models.ManyToManyField(to='home.TagModel', verbose_name='list_tag'),
        ),
    ]
