# Generated by Django 3.2 on 2021-05-05 03:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_cardmodel_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmodel',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 5, 8, 29, 49, 513593)),
        ),
    ]
