# Generated by Django 3.2 on 2021-05-20 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210519_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admingaxabar',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='usergajavob',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='admingaxabar',
            name='is_answer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usergajavob',
            name='savol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminga', to='home.admingaxabar'),
        ),
    ]
