# Generated by Django 3.2 on 2021-05-06 08:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_alter_cardmodel_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorgaXabar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 6, 13, 40, 0, 582444)),
        ),
        migrations.CreateModel(
            name='UsergaJavob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('javob', models.TextField()),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('savol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.operatorgaxabar')),
                ('send_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
