# Generated by Django 3.2 on 2021-05-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210520_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admingaxabar',
            name='is_answer',
        ),
        migrations.AddField(
            model_name='usergajavob',
            name='is_answer',
            field=models.BooleanField(default=True),
        ),
    ]
