# Generated by Django 3.1.7 on 2021-04-06 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210402_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmodel',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 6, 17, 52, 21, 782725)),
        ),
    ]
