# Generated by Django 3.1.7 on 2021-04-24 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_cardmodel_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmodel',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 24, 18, 6, 25, 821437)),
        ),
    ]
