# Generated by Django 3.2 on 2021-05-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='url',
            field=models.SlugField(blank=True, help_text='shart emas', max_length=60, null=True, verbose_name='user friendly url'),
        ),
    ]
