# Generated by Django 3.2 on 2021-05-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quiz_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='rating_quiz',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
