# Generated by Django 3.2 on 2021-05-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_rating_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
