# Generated by Django 3.2 on 2021-04-27 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='count_of_quizes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizcategory', to='quiz.category', verbose_name='Category'),
        ),
    ]
