# Generated by Django 3.2 on 2021-04-27 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20210427_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='count_of_quizes',
        ),
    ]
