# Generated by Django 3.2 on 2021-04-29 12:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_category_count_of_quizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Enter the question text that you want displayed', null=True, verbose_name='Question'),
        ),
    ]
