# Generated by Django 3.1.7 on 2021-04-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210424_1806'),
        ('quiz', '0002_auto_20210423_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='tag',
            field=models.ManyToManyField(to='home.TagModel'),
        ),
    ]
