# Generated by Django 3.1.7 on 2021-03-23 09:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 23, 9, 5, 53, 636397, tzinfo=utc)),
        ),
    ]
