# Generated by Django 3.1.7 on 2021-03-23 09:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210323_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 23, 9, 6, 19, 80409, tzinfo=utc)),
        ),
    ]
