# Generated by Django 3.1.7 on 2021-03-24 14:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210323_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 24, 14, 45, 42, 547230, tzinfo=utc)),
        ),
    ]
