# Generated by Django 3.1.7 on 2021-03-24 18:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20210324_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 24, 18, 26, 19, 163324, tzinfo=utc)),
        ),
    ]
