# Generated by Django 3.2 on 2021-05-01 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmodel',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 1, 16, 17, 55, 98432)),
        ),
    ]
