# Generated by Django 3.2 on 2021-05-06 17:26

import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='CourseListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs_name', models.CharField(max_length=100)),
                ('kurs_info', models.CharField(max_length=1000)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='img')),
                ('date_of_kurs', models.DateField(default=datetime.datetime(2021, 5, 6, 22, 26, 32, 23807))),
                ('number_of_view', models.IntegerField(default=0)),
                ('hour_of_course', models.IntegerField(default=0)),
                ('minut_of_course', models.IntegerField(default=0)),
                ('count_of_videos', models.IntegerField(default=0)),
                ('count_of_comments', models.IntegerField(default=0)),
                ('author_name', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReplyCommentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reply_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_comment', to='courses.commentcourse')),
            ],
        ),
        migrations.CreateModel(
            name='CourseVideoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(default='https://www.youtube.com/embed/')),
                ('video_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('video_time', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_video', to='courses.courselistmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_info', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='img')),
                ('tag', models.ManyToManyField(to='home.TagModel', verbose_name='tag_list')),
            ],
        ),
        migrations.AddField(
            model_name='courselistmodel',
            name='course',
            field=models.ManyToManyField(related_name='course_count', to='courses.CourseModel'),
        ),
        migrations.AddField(
            model_name='courselistmodel',
            name='tag',
            field=models.ManyToManyField(to='home.TagModel', verbose_name='tag_list'),
        ),
        migrations.AddField(
            model_name='commentcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='courses.courselistmodel'),
        ),
    ]
