# Generated by Django 3.1.7 on 2021-04-09 13:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2021, 4, 9, 13, 26, 42, 76616, tzinfo=utc))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs_name', models.CharField(max_length=100)),
                ('kurs_info', models.CharField(max_length=1000)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='img')),
                ('date_of_kurs', models.DateField(default=datetime.datetime(2021, 4, 9, 18, 26, 42, 70795))),
                ('number_of_view', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReplyCommentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2021, 4, 9, 13, 26, 42, 77834, tzinfo=utc))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reply_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_comment', to='courses.commentcourse')),
            ],
        ),
        migrations.CreateModel(
            name='CourseVideoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(default='https://www.youtube.com/embed/')),
                ('video_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('video_time', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_video', to='courses.courselistmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_info', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='img')),
                ('tag', models.ManyToManyField(to='home.TagModel', verbose_name='tag_list')),
            ],
        ),
        migrations.AddField(
            model_name='courselistmodel',
            name='course',
            field=models.ManyToManyField(to='courses.CourseModel'),
        ),
        migrations.AddField(
            model_name='courselistmodel',
            name='tag',
            field=models.ManyToManyField(to='home.TagModel', verbose_name='tag_list'),
        ),
        migrations.AddField(
            model_name='commentcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='courses.courselistmodel'),
        ),
    ]
