# Generated by Django 3.1.7 on 2021-04-09 16:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210409_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselistmodel',
            name='min_of_course',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commentcourse',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 16, 2, 1, 3104, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='courselistmodel',
            name='date_of_kurs',
            field=models.DateField(default=datetime.datetime(2021, 4, 9, 21, 2, 0, 996709)),
        ),
        migrations.AlterField(
            model_name='replycommentcourse',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 16, 2, 1, 4585, tzinfo=utc)),
        ),
    ]
