# Generated by Django 3.1.7 on 2021-04-09 16:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210409_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courselistmodel',
            old_name='min_of_course',
            new_name='minut_of_course',
        ),
        migrations.AlterField(
            model_name='commentcourse',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 16, 3, 4, 866797, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='courselistmodel',
            name='date_of_kurs',
            field=models.DateField(default=datetime.datetime(2021, 4, 9, 21, 3, 4, 860926)),
        ),
        migrations.AlterField(
            model_name='replycommentcourse',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 16, 3, 4, 868511, tzinfo=utc)),
        ),
    ]
