# Generated by Django 3.1.7 on 2021-04-14 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20210410_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentcourse',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterField(
            model_name='courselistmodel',
            name='date_of_kurs',
            field=models.DateField(default=datetime.datetime(2021, 4, 14, 17, 13, 7, 433650)),
        ),
    ]
