# Generated by Django 3.1.7 on 2021-04-15 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20210415_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselistmodel',
            name='count_of_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='courselistmodel',
            name='date_of_kurs',
            field=models.DateField(default=datetime.datetime(2021, 4, 15, 12, 15, 31, 721863)),
        ),
    ]
