# Generated by Django 3.1.7 on 2021-04-23 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20210415_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselistmodel',
            name='course',
            field=models.ManyToManyField(related_name='course_count', to='courses.CourseModel'),
        ),
        migrations.AlterField(
            model_name='courselistmodel',
            name='date_of_kurs',
            field=models.DateField(default=datetime.datetime(2021, 4, 23, 12, 37, 6, 937583)),
        ),
    ]
