# Generated by Django 3.2 on 2021-04-27 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20210424_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselistmodel',
            name='date_of_kurs',
            field=models.DateField(default=datetime.datetime(2021, 4, 27, 22, 42, 59, 664122)),
        ),
    ]
