# Generated by Django 3.1.7 on 2021-04-24 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_courselistmodel_date_of_kurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselistmodel',
            name='date_of_kurs',
            field=models.DateField(default=datetime.datetime(2021, 4, 24, 18, 6, 26, 670569)),
        ),
    ]
