# Generated by Django 3.1.7 on 2021-04-02 05:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20210402_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 2, 5, 18, 9, 862733, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
