# Generated by Django 3.1.7 on 2021-03-26 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='img')),
                ('text', models.TextField()),
                ('create_date', models.DateField(default=datetime.datetime(2021, 3, 26, 6, 2, 17, 850062))),
                ('tag', models.ManyToManyField(to='home.TagModel', verbose_name='tag_list')),
            ],
        ),
    ]
