# Generated by Django 3.1.7 on 2021-03-15 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmodel',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 15, 13, 50, 39, 461214)),
        ),
        migrations.AlterField(
            model_name='homemaqolamodel',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 15, 13, 50, 39, 464213)),
        ),
    ]
