# Generated by Django 3.1.7 on 2021-03-23 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210323_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmodel',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 23, 14, 5, 44, 312830)),
        ),
    ]
