# Generated by Django 3.1.7 on 2021-04-14 12:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20210410_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 14, 12, 13, 7, 468093, tzinfo=utc)),
        ),
    ]
