# Generated by Django 3.1.7 on 2021-04-02 05:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20210402_0458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='slug',
        ),
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 2, 5, 10, 36, 44976, tzinfo=utc)),
        ),
    ]
