# Generated by Django 3.1.7 on 2021-04-02 06:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20210402_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='slug',
        ),
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 2, 6, 20, 31, 715072, tzinfo=utc)),
        ),
    ]
