# Generated by Django 3.2 on 2021-05-01 11:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(upload_to='logo')),
                ('location', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 5, 1, 11, 17, 28, 847976, tzinfo=utc))),
                ('dedline', models.DateTimeField()),
                ('salary', models.CharField(max_length=50)),
                ('job_time', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('experience', models.TextField()),
                ('experience_time', models.CharField(max_length=50)),
                ('benifits', models.TextField()),
            ],
        ),
    ]
