# Generated by Django 3.1.7 on 2021-04-24 13:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_jobsmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 13, 6, 26, 692591, tzinfo=utc)),
        ),
    ]
