# Generated by Django 3.1.7 on 2021-04-13 07:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20210410_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentblogmodel',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 13, 12, 28, 20, 389451)),
        ),
        migrations.AlterField(
            model_name='commentblogmodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='replycommentblogmodel',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 13, 7, 28, 20, 393562, tzinfo=utc)),
        ),
    ]
