# Generated by Django 3.1.7 on 2021-04-15 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20210415_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='count_of_blog',
            new_name='count_of_view',
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 15, 12, 47, 30, 331928)),
        ),
    ]
