# Generated by Django 3.2 on 2021-04-23 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20210423_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 23, 12, 48, 3, 436375)),
        ),
    ]
