# Generated by Django 3.2 on 2021-05-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('info', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='books')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(max_length=100)),
                ('tag', models.ManyToManyField(to='home.TagModel')),
            ],
        ),
    ]
