# Generated by Django 3.1.7 on 2021-04-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210414_1716'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='tag',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='tag',
            field=models.ManyToManyField(to='home.TagModel'),
        ),
    ]
